<?
/*
@file
	PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time it is updated.

@version
	0.1

@warning
	This file requires that the include path contain the Custodian CMS
	library directories, this is not auto-set. If required, you can
	enable this using the ini_set() function below, simply uncomment
	it and reload the page.

@Copyright
	Custodian CMS v0.1 - Content Management System (CMS)
	Copyright (C) 2013 - Vincent A Hallberg, modusinternet.com

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	Visit http://www.gnu.org/copyleft/lesser.html to read online; or
	write to the Free Software Foundation, Inc., 51 Franklin Street,
	Fifth Floor, Boston, MA  02110-1301  USA for a copy.
 */

$CFG = array();
$CLEAN = array();
$ccms_whitelist = array();
$user_whitelist = array();

require_once "ccmspre/config.php";

// Use the ini_set function to set value of the include_path option on your server if necessary.
// e.g.: ini_set('include_path', 'ccmsadm:ccmslib:ccmspre:ccmstpl' . ini_get('include_path'));
//ini_set('include_path', $CFG["ADMDIR"] . ':' . $CFG["LIBDIR"] . ':' . $CFG["PREDIR"] . ':' . $CFG["TPLDIR"] . ':' . ini_get('include_path'));


ob_start("ob_gzhandler");

// Testing to see if we should be displaying debug information or not.
if($CFG["DEBUG"] == 1 && ($CFG["DEBUGIPSONLY"] == "" || stristr($CFG["DEBUGIPSONLY"], $_SERVER["REMOTE_ADDR"]) !== FALSE)) {
	echo "Debug enabled.  Your IP is [" . $_SERVER["REMOTE_ADDR"] . "]<br />\n";
	echo "\$CFG[\"DEBUGIPSONLY\"] = [";
	if($CFG["DEBUGIPSONLY"] == "") {
		echo "<b>Any IP Address</b>";
	} else {
		echo $CFG["DEBUGIPSONLY"];
	}
	echo "]<br />\n";
}

if($CFG["DEBUG"] == 1 && $CFG["DEBUG_ERROR_REPORTING"] == 1) error_reporting(E_ALL);

/*
	HTML Purifier is a standards-compliant HTML filter library written in PHP. HTML Purifier will
	not only remove all malicious code (better known as XSS) with a thoroughly audited, secure yet
	permissive whitelist, it will also make sure your documents are standards compliant.
	http://htmlpurifier.org/

	This library is not required by nor a part of Custodian CMS; thus not enabled by default.
	It is however bundled with Custodian CMS because it is a fantastic tool and will be used
	in the near future as the basecode and plug-ins designed to work with Custodian CMS
	continue to be developed.
*/
//require_once $CFG["PREDIR"] . '/htmlpurifier/HTMLPurifier.standalone.php';
//$purifier = new HTMLPurifier();
//$clean_html = $purifier->purify($dirty_html);

require_once $CFG["PREDIR"] . '/user_whiteList.php';
require_once $CFG["PREDIR"] . '/index.php';

if($CFG["DEBUG"] == 1) {
	echo "<span style=\"color:red;\">\$_SERVER=[<pre>";
	print_r($_SERVER);
	echo "</pre>]</span><br />\n";
	echo "<span style=\"color:red;\">\$_REQUEST=[<pre>";
	print_r($_REQUEST);
	echo "</pre>]</span><br />\n";
}
// This creats a initial connection to MySQL so that we can use the
// mysql_real_escape_string() where ever we want later.
CCMS_dbFirstConnect();

CCMS_filter($_SERVER + $_REQUEST, $ccms_whitelist);
USER_filter($_SERVER + $_REQUEST, $user_whitelist);
if($CFG["DEBUG"] == 1) {
	echo "<span style=\"color:green;\">\$CLEAN=[<pre>";
	print_r($CLEAN);
	echo "</pre>]</span><br />\n";
}

CCMS_go();
?>